version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-laravel-app
    container_name: docker-laravel-app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: docker-laravel-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel
    volumes:
      - mysql_data:/var/lib/mysql

  db:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data: